//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Entidades;
    
    public partial class CulturillaEntities : DbContext
    {
        public CulturillaEntities()
            : base("name=CulturillaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Correcta> Correctas { get; set; }
        public DbSet<Erronea> Erroneas { get; set; }
        public DbSet<Pregunta> Preguntas { get; set; }
    }
}
