//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        public Pregunta()
        {
            this.Correctas = new HashSet<Correcta>();
            this.Erroneas = new HashSet<Erronea>();
        }
    
        public int ID { get; set; }
        public string Descripción { get; set; }
    
        public virtual ICollection<Correcta> Correctas { get; set; }
        public virtual ICollection<Erronea> Erroneas { get; set; }
    }
}
